spring.application.name=eCommerce

spring.jpa.hibernate.ddl-auto=update
spring.datasource.url=jdbc:postgresql://localhost:5432/ecommerce_db
spring.datasource.username=ecommerce_app
spring.datasource.password=ecom123
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

api_prefix=/api/v1

auth.token.expirationInMills=3600000
auth.token.jwtSecret=36763979244226452948404D635166546A576D5A7134743777217A25432A462D

baseURL=http://localhost:8081/

# Use Stripe Secret Key
STRIPE_SECRET_KEY=<STRIP_SECRET_KEY>
